version: "3"
services:
  proxy:
    container_name: "proxy"
    build: ./proxy
    ports:
      - "8080:8080"
      - "9901:9901"
    links:
      - "backend"
    depends_on:
      - "backend"

  backend:
    container_name: "backend"
    build: ./backend
    volumes:
      - ./backend/:/go/src/grpc-web-sample/backend
    ports:
      - "9090:9090"

  frontend:
    container_name: "frontend"
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
